services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=sensordb
      - GF_DATABASE_USER=dbuser
      - GF_DATABASE_PASSWORD=secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./grafana-provisioning/datasource/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana-data:/var/lib/grafana
